server:
  port: ${random.int(5100,5200)}
  servlet:
    context-path: /sie-api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uady
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
